/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_gudenau_lib_largebuffers_implementation_NativeMethods */

#ifndef _Included_net_gudenau_lib_largebuffers_implementation_NativeMethods
#define _Included_net_gudenau_lib_largebuffers_implementation_NativeMethods
#ifdef __cplusplus
extern "C" {
#endif
#undef net_gudenau_lib_largebuffers_implementation_NativeMethods_NULL
#define net_gudenau_lib_largebuffers_implementation_NativeMethods_NULL 0LL
/*
 * Class:     net_gudenau_lib_largebuffers_implementation_NativeMethods
 * Method:    doGetAddressSize
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_net_gudenau_lib_largebuffers_implementation_NativeMethods_doGetAddressSize
  (JNIEnv *, jclass);

/*
 * Class:     net_gudenau_lib_largebuffers_implementation_NativeMethods
 * Method:    doAllocateMemory
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_net_gudenau_lib_largebuffers_implementation_NativeMethods_doAllocateMemory
  (JNIEnv *, jclass, jlong);

/*
 * Class:     net_gudenau_lib_largebuffers_implementation_NativeMethods
 * Method:    doFreeMemory
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_net_gudenau_lib_largebuffers_implementation_NativeMethods_doFreeMemory
  (JNIEnv *, jclass, jlong);

/*
 * Class:     net_gudenau_lib_largebuffers_implementation_NativeMethods
 * Method:    domemset
 * Signature: (JBJ)V
 */
JNIEXPORT void JNICALL Java_net_gudenau_lib_largebuffers_implementation_NativeMethods_domemset
  (JNIEnv *, jclass, jlong, jbyte, jlong);

/*
 * Class:     net_gudenau_lib_largebuffers_implementation_NativeMethods
 * Method:    domemcpy
 * Signature: (JJJ)V
 */
JNIEXPORT void JNICALL Java_net_gudenau_lib_largebuffers_implementation_NativeMethods_domemcpy
  (JNIEnv *, jclass, jlong, jlong, jlong);

/*
 * Class:     net_gudenau_lib_largebuffers_implementation_NativeMethods
 * Method:    doGetBoolean
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_net_gudenau_lib_largebuffers_implementation_NativeMethods_doGetBoolean
  (JNIEnv *, jclass, jlong);

/*
 * Class:     net_gudenau_lib_largebuffers_implementation_NativeMethods
 * Method:    doGetByte
 * Signature: (J)B
 */
JNIEXPORT jbyte JNICALL Java_net_gudenau_lib_largebuffers_implementation_NativeMethods_doGetByte
  (JNIEnv *, jclass, jlong);

/*
 * Class:     net_gudenau_lib_largebuffers_implementation_NativeMethods
 * Method:    doGetShort
 * Signature: (J)S
 */
JNIEXPORT jshort JNICALL Java_net_gudenau_lib_largebuffers_implementation_NativeMethods_doGetShort
  (JNIEnv *, jclass, jlong);

/*
 * Class:     net_gudenau_lib_largebuffers_implementation_NativeMethods
 * Method:    doGetInt
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_net_gudenau_lib_largebuffers_implementation_NativeMethods_doGetInt
  (JNIEnv *, jclass, jlong);

/*
 * Class:     net_gudenau_lib_largebuffers_implementation_NativeMethods
 * Method:    doGetLong
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_net_gudenau_lib_largebuffers_implementation_NativeMethods_doGetLong
  (JNIEnv *, jclass, jlong);

/*
 * Class:     net_gudenau_lib_largebuffers_implementation_NativeMethods
 * Method:    doPutBoolean
 * Signature: (JZ)V
 */
JNIEXPORT void JNICALL Java_net_gudenau_lib_largebuffers_implementation_NativeMethods_doPutBoolean
  (JNIEnv *, jclass, jlong, jboolean);

/*
 * Class:     net_gudenau_lib_largebuffers_implementation_NativeMethods
 * Method:    doPutByte
 * Signature: (JB)V
 */
JNIEXPORT void JNICALL Java_net_gudenau_lib_largebuffers_implementation_NativeMethods_doPutByte
  (JNIEnv *, jclass, jlong, jbyte);

/*
 * Class:     net_gudenau_lib_largebuffers_implementation_NativeMethods
 * Method:    doPutShort
 * Signature: (JS)V
 */
JNIEXPORT void JNICALL Java_net_gudenau_lib_largebuffers_implementation_NativeMethods_doPutShort
  (JNIEnv *, jclass, jlong, jshort);

/*
 * Class:     net_gudenau_lib_largebuffers_implementation_NativeMethods
 * Method:    doPutInt
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_net_gudenau_lib_largebuffers_implementation_NativeMethods_doPutInt
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     net_gudenau_lib_largebuffers_implementation_NativeMethods
 * Method:    doPutLong
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_net_gudenau_lib_largebuffers_implementation_NativeMethods_doPutLong
  (JNIEnv *, jclass, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
